### ISSUE TITLE
fault seems to capture output by default?

### ISSUE THREAD

**Issue by THofstee** [leonardt/fault#128]
When I run `tester.compile_and_run` it silently completes. This is running a testbench through VCS with display statements. I should expect to see compilation logs from VCS, as well as the actual testbench results from the test that was run.

Even if the intended behavior is to be silent on success, this is unintuitive to me. Can there at least be a verbose/quiet flag?

**Comment by leonardt** [comment]
All the output from fault has been moved to use the `logging` module. This was because the simulator output was slowing down/crashing huge test runs. To see the output, you can do

```
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
```
This will dump everything through the logging output (e.g. verilator command output)

If you want to see some output, but less verbose, you can do
```
import logging
logger = logging.getLogger()
logger.setLevel(logging.INFO)
```
(Here's an example of the INFO level from https://github.com/leonardt/magma_register_file_tutorial/blob/master/4-Using%20the%20Register%20File.ipynb)
```
In [10]: test_top_write_then_reads("distribute", 2)
root - INFO - Running tester...
root - INFO - Success!
```
