### ISSUE TITLE
random_uint and random_sint

### ISSUE THREAD

**Issue by sgherbst** [leonardt/fault#81]
Just a minor suggestion -- I think it would be good to have **random_sint** and **random_uint** functions to go along with the **random_bit** and **random_bv** functions already defined in fault/random.py.

**Comment by phanrahan** [comment]
I second this suggestion.

**Comment by leonardt** [comment]
The `hwtypes` Python classes now provide `random` static methods, (e.g. https://github.com/leonardt/hwtypes/blob/master/hwtypes/bit_vector.py#L429-L431), so I propose that we leverage the `hwtypes` interface for generating random values rather than duplicate the code in the fault package. We can reserve `fault.random` for more complex generation of random values.
